[package]
name = "keym-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
windows = { version = "0.52", features = [
    "Win32_Foundation",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
]}
lazy_static = "1.4"
spin_sleep = "1.1"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
panic = 'abort'