toggle_key = ""

[[macros]]
trigger = "1"
mode = 2

[[macros.actions]]
key = "5"
hold_ms = 50
delay_ms = 50

[[macros.actions]]
key = "8"
hold_ms = 50
delay_ms = 50

[[macros.actions]]
key = "5"
hold_ms = 50
delay_ms = 50

[[macros.actions]]
key = "3"
hold_ms = 50
delay_ms = 50

[[macros.actions]]
key = "f"
hold_ms = 50
delay_ms = 50

[[macros.actions]]
key = "g"
hold_ms = 50
delay_ms = 50

[[macros.actions]]
key = "j"
hold_ms = 50
delay_ms = 50
