[package]
name = "keym-editor"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "keym-editor"
path = "src/main.rs"

[dependencies]
shared = { path = "../shared" }
native-windows-gui.workspace = true
native-windows-derive.workspace = true